### ISSUE TITLE
Fill documentation for operations

### ISSUE THREAD

**Issue by hheenen** [libAtoms/workflow#101]
Go through documentations for operations (https://libatoms.github.io/workflow/operations.html), test the examples, and fill the sections with explanations and some examples.

**Comment by gelzinyte** [comment]
The main idea - so people get a quick overview of what modular "operations"/"tasks" are available in Workflow. Doesn't have to be very involved, maybe 2-3 sentences. For detailed explanation, users should check the auto-documented [docstrings](https://libatoms.github.io/workflow/modules.html). And for examples, they should go to appropriate (linked) example in [Examples](https://libatoms.github.io/workflow/examples.html)
