### ISSUE TITLE
Review barebones code snippets in Examples

### ISSUE THREAD

**Issue by gelzinyte** [libAtoms/workflow#105]
Simplify if needed, catch any bugs and add comments, so [Examples](https://libatoms.github.io/workflow/examples.html) are useful.

[maybe post docathon - do this in a format that can be automatically converted into a pretty sphinx doc and an executable, so they can be run automatically for testing purposes]

**Comment by Zausinator** [comment]
I'll review the code snippets, and will add our "barebones" iterative fitting process (although I might make a separate issue for that).

RE the DFT-calculations: Might be I run into problems there, but we'll see.

**Comment by gelzinyte** [comment]
Thanks! A slightly extended example of iterative fitting process would be very useful (an issue #115 ). 

For DFT calculators - just add/check example for those calculators that you have access to. 

Btw multiple people can work on this issue, going over one example (as a separate .html page) at a time.

**Comment by gelzinyte** [comment]
I'll start working on this one file at a time
