### ISSUE TITLE
Generalize Autoparallelize inputs

### ISSUE THREAD

**Issue by Zausinator** [libAtoms/workflow#147]
As mentioned [here](https://github.com/libAtoms/workflow/pull/121), running certain functions in parallel does not work in an intuitive manner. A common occurence is that the function you're running gives the output:
```
Running wfl.generate.md.sample_autopara_wrappable with num_python_subprocesses=4, num_inputs_per_python_subprocess=None
```
Thus not running anything in parallel, but in series.

I'm guessing the most straightforward solve would be to default the ```num_inputs_per_python_subprocesses``` to the most logical integer, depending on the length of the input iterable and the ```num_python_subprocesses```.

**Comment by noambernstein** [comment]
Unfortunately, you can’t count on its table to have a known length, so
we’ll have to pick a universal default. Could be 10, if we assume most
operations are cheap, or 1, if we assume most operations don’t have a large
startup cost.

**Comment by bernstei** [comment]
I have a fix in progress.  PR coming soon.
