### ISSUE TITLE
traj_select_during_func in wfl/generate/md/__init__.py not working as expected

### ISSUE THREAD

**Issue by simonwengert** [libAtoms/workflow#149]
When running an md via the `sample()` function in combination with using the `traj_select_during_func` option, the last image of an MD does not have to pass the `traj_select_during_func` function. Thus, for instance with a selection-function that will not less any atom pass, the `sample()` function will still return atoms-objects. Tested for instance with the following function
```
def traj_select_during_func(atoms):
    return False
```
I believe the issue is related to this code block in `wfl/generate/md/__init__.py` (Line 224-226)
```
if len(traj) == 0 or traj[-1] != at:
    at.info['MD_time_fs'] = cur_step * dt
    traj.append(at_copy_save_results(at, results_prefix=results_prefix))
```
where the `traj[-1] != at` is very likely to be fulfilled when using  `traj_select_during_func`.

A possible solution would be 
```
if len(traj) == 0 or traj[-1] != at:
    if traj_select_during_func is None or traj_select_during_func(at):
        at.info['MD_time_fs'] = cur_step * dt
        traj.append(at_copy_save_results(at, results_prefix=results_prefix))
```

**Comment by bernstei** [comment]
Do we agree that MD sampling should always return at least the last configuration? Or if a user passes a trajectory selection function that thinks nothing should be returned, it should return nothing?

**Comment by simonwengert** [comment]
I think it would be more intuitive to let the function return nothing if the specified criterion of the selection function is too tight. (And the user might better rethink the specified criterion in such cases)

**Comment by bernstei** [comment]
I tend to agree.  Can you create a PR with your proposed solution?

BTW, what do you think of having the function parameter being `traj_select_during_func=lambda at: True` instead of `None`, so we don't have to test for it being `not None`?

**Comment by simonwengert** [comment]
> BTW, what do you think of having the function parameter being `traj_select_during_func=lambda at: True` instead of `None`, so we don't have to test for it being `not None`?

I like the idea.
