### ISSUE TITLE
`WFLFileIOCalculator` doesn't clean up after itself 

### ISSUE THREAD

**Issue by gelzinyte** [libAtoms/workflow#161]
When a `scratchdir` is used, for the individual calculation, a many directories get created in `scratchdir`, to reflect the absolute path to the folder where the calculation was called from ([line](https://github.com/libAtoms/workflow/blob/e66ac6420c9256ff81cc80a46639d1c58503af00/wfl/calculators/wfl_fileio_calculator.py#L54)). After calculation the files are just copied over and the many directories are left dangling, I think they should be cleaned up. 

I would create a single directory in `scratchdir` and delete it after the files have been moved. The single directory name could be either just the tempdir filename or a name made out of the `workdir/rundir_prefix`, e.g. by replacing all `/` with `_`. 

@bernstei what do you think?

**Comment by bernstei** [comment]
I was assuming that (HPC) systems have an automated process for cleaning up scratch space, e.g. based on file age, but I'm happy to support the situation where we have to do our own cleanup (maybe by default). If we want to support both approaches, I'd suggest keeping the scratch dir name that's the same as the final dir name, but I'm happy to have an (optional, happy to make the default true) `clean_scratchdir` argument which recursively deletes the per-config scratch dir.  Do you want to code it up, or should I?

**Comment by gelzinyte** [comment]
I can add that to #162. 

If we add a (default) option to clean `scratchdir`, why not to always do it (would make coder simpler, fewer choices/arguments to think about) and have both approaches? 

> keeping the scratch dir name that's the same as the final dir name

Do you mean full path or just the unique dir name generated by `tempfile`? 

There would be multiple `{rundir_prefix}random` created and deleted throughout the job. If one of the instances tries to recursively delete everything after `/scratch-dir/` (e.g. `/scratch-dir/home/user/path/to/project/workdir/{rundir_prefix}random1`) and another at the same time create `/scratch-dir/home/user/path/to/project/workdir/{rundir_prefix}random2` wouldn't that potentially cause problems?

**Comment by bernstei** [comment]
> If we add a (default) option to clean `scratchdir`, why not to always do it (would make coder simpler, fewer choices/arguments to think about) and have both approaches?

I'm confused.  What "it" do you mean by "always do it", and what "both" approaches do you mean?

> 
> > keeping the scratch dir name that's the same as the final dir name
> 
> Do you mean full path or just the unique dir name generated by `tempfile`?

Either - I mean keep the one-to-one mapping between scratch subdir names and resulting in the main rundir final per-config subdirectories.

> 
> There would be multiple `{rundir_prefix}random` created and deleted throughout the job. If one of the instances tries to recursively delete everything after `/scratch-dir/` (e.g. `/scratch-dir/home/user/path/to/project/workdir/{rundir_prefix}random1`) and another at the same time create `/scratch-dir/home/user/path/to/project/workdir/{rundir_prefix}random2` wouldn't that potentially cause problems?

I don't think anything should try to recursively delete above the per-config directory that it created:
```
create per-config rundir
create scratchdir with corresponding name
do run in scratchdir
copy files from scratchdir to rundir
optionally delete scratchdir with corresponding name
```

**Comment by gelzinyte** [comment]
> I'm confused. What "it" do you mean by "always do it", and what "both" approaches do you mean?

I'm just wondering why to have a `clean_scratchdir` option and not to always delete the calculation directory. 

For the rest - let me add a proposal and we can discuss on the PR.

**Comment by bernstei** [comment]
I don't actually have strong feelings about cleaning `scratchdir`, as long as we're careful that it won't delete anything it shouldn't.  Just in general deleting things makes me nervous. But since your use case is the main one for `scratchdir`, I'm happy to implement whatever details you think you need.
