### ISSUE TITLE
Online documentation does not display `docs/source/wfl.generate.md.rst`

### ISSUE THREAD

**Issue by simonwengert** [libAtoms/workflow#168]
When generating the html *circular toctree references* are detected. I suspect the *.md extension causes some confusion here.

**Comment by bernstei** [comment]
Yes - I opened this https://github.com/sphinx-doc/sphinx/issues/10914

I don't see any way to fix this without renaming our md module or changing sphinx internals.

**Comment by gelzinyte** [comment]
I think this is fixed now?

**Comment by bernstei** [comment]
Yes, closing now.  If #169's description had the line `closes #168` it would have happened automatically.
