### ISSUE TITLE
Re-enable syntax highlighting for auto-tested `examples`

### ISSUE THREAD

**Issue by simonwengert** [libAtoms/workflow#204]
While establishing auto-tested examples in our documentation via jupyter notebooks, we have lost the syntax highlight (compare e.g. https://libatoms.github.io/workflow/examples.buildcell.html vs. https://libatoms.github.io/workflow/examples.orca_python.html). 

The `build-docs action` states `/home/runner/work/workflow/workflow/docs/source/examples.buildcell.ipynb:: WARNING: Pygments lexer name 'ipython3' is not known`. 

From what I read so far, it might be as simple as installing `ipython` to get the syntax back. See https://stackoverflow.com/questions/60187649/nbsphinx-syntax-highlighting-on-readthedocs and https://nbsphinx.readthedocs.io/en/0.6.0/installation.html#Pygments-Lexer-for-Syntax-Highlighting. 

Unfortunately, when testing things locally, I always see the syntax highlighting. Thus, I can't really test if this will fix the publicly visible documentation.

@noambernstein If I understand it correctly, the online documentation gets updated when its merged into `main`(?) For testing the solution we could merge the described solution and see if it works. I see that this is not really a good practice. On the other hand, I don't see another way how to test it, and it's only a minor change that shouldn't affect anything else. 
@noambernstein The `build-docs action` includes the deployment of the online documentation, right?. So, appending `ipython` to the `Install dependencies from pip` section would fix it.

**Comment by bernstei** [comment]
I'll try it.

**Comment by bernstei** [comment]
I just merged another attempt at a workaround

**Comment by bernstei** [comment]
Looks to me like this workaround was sufficient, right @simonwengert  ?

**Comment by simonwengert** [comment]
Yes, that solved it! Syntax highlights are back.
