### ISSUE TITLE
Overwriting of output-file fails for functions that go through `autoparallelize`

### ISSUE THREAD

**Issue by bapatist** [libAtoms/workflow#208]
Hello
For instance, when a file path to `abc.xyz` exists and we wish to overwrite this file using 
``` python
from wfl.descriptors.quippy import calc
```
 When first declaring `out_config = OutputSpec(files='abc.xyz', overwrite=True)` and calling `calc` with argument `outputs=out_config` I get the error 

`Returning before <function _calc_autopara_wrappable at 0x1479f0ad5d30> since output is done`

This appears to come from (https://github.com/libAtoms/workflow/blob/main/wfl/autoparallelize/base.py) line 233-236:
``` python
         if outputspec.done():
             sys.stderr.write(f'Returning before {op} since output is done\n')
             return outputspec.to_ConfigSet()
```
A solution can be to add `self.overwrite = overwrite` in the `__init__` function of the `OutputSpec` object and then change `base.py` line (233-236) to:
``` python
         if outputspec.done() and outputspec.overwrite == False:
             sys.stderr.write(f'Returning before {op} since output is done\n')
             return outputspec.to_ConfigSet()
```
Alternatively, this works as well: (along with `self.overwrite = overwrite` in the `__init__`), changing the `done` function in OutputSpec object from
``` python
    def done(self):
        if self.files is not None:
            return all([(self.file_root / f).exists() for f in self.files])
```
to
``` python
    def done(self):
        if self.files is not None and self.overwrite == False:
            return all([(self.file_root / f).exists() for f in self.files])
```
In its current state, the `overwrite` argument works as expected when set to `False` and whenever OutputSpec is used with non-autoparallelized functions, but, not when set to `True` and used with functions that call autoparallelize.
Please let me know your thoughts or any questions. Thanks.

**Comment by bernstei** [comment]
I agree that this looks like just a bug, but I want to think about your solution a bit more.  

Would you be willing to add a test that fails with the current version?

**Comment by bapatist** [comment]
Sure, I will add it

**Comment by bernstei** [comment]
I think this is worth more thought. Is "`overwrite = True`" just permission for the `OutputSpec` to overwrite, and we should have a separate argument passed to autoparallelized functions to _not_ skip even if it appears to be done? Or should the autoparallelized functions take their cue from something like `OutputSpec.overwrite`?  I'll ask in the slack channel as well.

**Comment by bapatist** [comment]
I agree. `OutputSpec.overwrite` and `OutputSpec.done` are making conflicts and could possibly be merged. Will have to think more about it as well.

**Comment by bernstei** [comment]
I guess I think that if `overwrite` was set to True, `done()` should return False. If you're willing to allow overwriting you're saying that you don't care what was previously in that file, in which case `done()` cannot know if it's the right thing (just using the filename is already a slightly dangerous assumption), so should return False.  It'll never be wrong, just inefficient.

**Comment by bapatist** [comment]
Yes, that sounds right. If `done()` is only really used to check for the file's existence, perhaps it can be used to only throw a warning and display the submitted boolean for `overwrite`. In the case when it is set to False but the file path exists, we should see an error (which the current version already rightly does)
Sharing the test example for which overwriting fails at the moment.

**Comment by bernstei** [comment]
conceptually, `done()` is used to check that the operation writing to the OutputSpec is done.  Right now that's assumed to be the case if all the files exist, because it should not be possible if the previous run failed or was killed before completion (because files are saved to temporary names and renamed only at the successful end,).

**Comment by bapatist** [comment]
I see! Actually the reason why this appeared as an issue at all was while going over iterations of fitting a potential, often I am required to resume the workflow from a certain breaking/error point for which, I assumed that setting `overwrite = True` would redo it and continue the chain without having to delete all the intermediate files as preparation. In hindsight, the error prompt `output is already done` is indeed true here. 
I expected workflow to still continue the code (maybe with a warning) since, as a user, I explicitly asked for an `overwrite = True`.  But I agree that in other cases, a file by that name will only exist if somehow it was placed there externally which is a probably an unlikely scenarios (but maybe should still be dealt with?)
A second concern is that in its current state, the overwrite feature is inconsistent, as it doesn't check for `done()` for functions that don't call `autoparallelize` (for example, while generating dimer configs). For which, overwriting is done even when the file exists (irrespective of its content).

**Comment by bernstei** [comment]
> I see! Actually the reason why this appeared as an issue at all was while going over iterations of fitting a potential, often I am required to resume the workflow from a certain breaking/error point for which, I assumed that setting `overwrite = True` would redo it and continue the chain without having to delete all the intermediate files as preparation. In hindsight, the error prompt `output is already done` is indeed true here. I expected workflow to still continue the code (maybe with a warning) since, as a user, I explicitly asked for an `overwrite = True`. 

Perhaps it's less obvious than I assumed that naming the argument `overwrite` implies that it'll write the output file _again_, which can only happen if it does the actual operation again.  The default behavior is for "workflow operations" that use `OutputSpec` to use `done()` to decided if to skip the operation. If they use `autoparallelize` that's automatic, and for the ones that don't, I've written them (or at least I intended to) so they do the same check and skip.

> But I agree that in other cases, a file by that name will only exist if somehow it was placed there externally which is a probably an unlikely scenarios (but maybe should still be dealt with?) 

Since `OutputSpec` can be used in arbitrary ways, I intended it to refuse to overwrite existing files by default.

> A second concern is that in its current state, the overwrite feature is inconsistent, as it doesn't check for `done()` for functions that don't call `autoparallelize` (for example, while generating dimer configs). For which, overwriting is done even when the file exists (irrespective of its content).

I'm not sure what you mean by inconsistent. I don't think anything I've written overwrites unless you pass `overwrite=True`.  My intention (of course there could be bugs) is that every `wfl` function that uses `OutputSpec` will either skip (_not overwrite_, just keep the existing file) or do the operation.  If you write your own function which takes an `OutputSpec`, it's up to you to deal with existing files however you think is safe.

Do you think some of these aspects need to be made more clear?  In the online docs?  The docstrings?  Change some of the names of the arguments?  I sort of agree that `done` as an argument to *`OutputSpec`* may be misleading - it's not the OutputSpec itself that's done, it's the operation that used it.  Maybe change it to `all_written` ?

**Comment by bapatist** [comment]
Thanks for the explanation. The functionality of `done()` and `overwrite` is clearer to me now. 
So in the case when file exists, it is assumed the operation is done already. So, there is nothing to write/overwrite. Just that at first glance, I connected over(writing) with re(doing) of the operation which are two different things and which made me think this is a bug (and the fact that it responded differently for two different `wfl` operations). 
Besides, for my code, I probably don't need to write the descriptors file at all if I can use it as a temporary variable within my iterative workflow. But anyway, that is outside the discussion.

**Comment by bapatist** [comment]
Other than possibly changing function name of `done` to `all_written`, I am not sure about documenting. Depends on whether users consider setting `overwrite=True` as a method to redo+rewrite as I did.

**Comment by bernstei** [comment]
> Depends on whether users consider setting `overwrite=True` as a method to redo+rewrite as I did.

I don't think I understand - can you explain in more detail what exactly you thought would happen when you passed `overwrite=True`?

**Comment by bapatist** [comment]
Okay, it is not an error but just a message indeed. There was a misunderstanding, sorry. The updated message makes it clearer now. 
Thanks for looking into it! I will close the issue now.
