### ISSUE TITLE
QE test xfail

### ISSUE THREAD

**Issue by bernstei** [libAtoms/workflow#22]
Test of pwscf via `Espresso` calculator of an actual converged calculation is broken. The default parameters fail to converge, and pwscf returns an error status after 100 iterations.  The new `Espresso` detects this as a convergence failure. Loosening the convergence tolerance allows it to stop without apparent failure, but then the hard-coded values are wrong.  

I suggest finding some system/parameters where convergence _is_ achieved, so the return values can be meaningfully tested.

**Comment by gelzinyte** [comment]
Fixed in #136 & #154
