### ISSUE TITLE
MACE calculator remote

### ISSUE THREAD

**Issue by Felixrccs** [libAtoms/workflow#273]
So I tried to the ASE-MACE calculator (v. 0.2.0 dev-branch) remote [GPU], while my local system has only [CPUs]. The problem is when it constructs the pickle save calculator locally, it fails to construct it because I have no GPU locally.

Any idea how to solve this issue?
Further is this a ```US/WFL``` problem or is this a ```MACE-guys``` problem?

I currently circumvent this problem by using expyre to sync my mace_model to my remote and then calling the wfl function there via expyre as well.

**Comment by bernstei** [comment]
Are you passing a calculator, or the 3-tuple `(constructor, args, kwargs)`? The latter should work, because it doesn't actually run the constructor until it's inside the autoparallelized job

**Comment by Felixrccs** [comment]
Ok I managed to get it to work, I had an error in my script.
