### ISSUE TITLE
`setup.py` doesn't install submodules. 

### ISSUE THREAD

**Issue by gelzinyte** [libAtoms/workflow#3]
All modules need to be listed in `setup.py`, not just `packages=["wfl"]`. Same goes for UniversalSOAP and ExPyRe. Would ` packages=setuptools.find_packages(exclude=["test"])` do what you wanted to do in `cc4aceb`? 

Though I've tried that and no modules get listed still (but wfl works):
```
In [1]: import wfl

In [2]: dir(wfl)
Out[2]:
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']
```

**Comment by noambernstein** [comment]
They are no longer sub modules, but dependencies. Those are listed in
setup.put (should be) and It should get those automatically from github.

**Comment by bernstei** [comment]
Oh, OK, I misunderstood.  Yes, `find_packages(exclude` is the right way to do things.  I'll fix it.

**Comment by bernstei** [comment]
However, I also realized that `make html` is using the _installed_ `wfl`, not the current source tree, which I think is going to be confusing.  Can I add "${PWD}/.." to PYTHONPATH in `docs/Makefile`?

**Comment by bernstei** [comment]
I think the `find_packages` stuff should be fixed everywhere.  Is it normal to get lots of warnings about the docstrings?

**Comment by bernstei** [comment]
I'm cleaning up the docstrings to reduce the amount of output from `make html`.  Maybe half way done so far?

**Comment by bernstei** [comment]
@gelzinyte can you confirm that I've fixed the submodule stuff in the latest version? I'd like to close this issue, and we can deal with the docs in another one.

**Comment by bernstei** [comment]
You may need to remove the current expyre-wfl and universalSOAP installations, because I had to update `setup.py` in those as well.

**Comment by gelzinyte** [comment]
Yes, thank you for fixing this.
