### ISSUE TITLE
`config_type` get concatenated over different operations

### ISSUE THREAD

**Issue by jungsdao** [libAtoms/workflow#310]
It is common to do multiple operations like optimizations and NEB calculation on the same config. 
After trying a few operations in that way I found that `config_type` has weird value like this. 
` 'config_type': 'optimize_last_converged_optimize_last_converged_neb_last_converged'`

I think it does make sense to keep only the last operations rather than keeping the history of all the operations. 
Also, `info` & `arrays` dictionary have two properties like 
'optimize_energy', 'neb_energy'
'optimize_forces', 'neb_forces'
Which could give confusion in case if the final operation was NEB calculation, it's still containing unrelated information about "optimization". 
I can probably select which value is relevant, but at this stage, optimize_energy and optimize_forces are totally redundant. 
I just wanted to point out this issue.

**Comment by bernstei** [comment]
Apparently, I thought of some of these things before:`wfl.generate.optimize` already has a `results_prefix` argument (as do `md` and `neb`). In fact, `wfl.generate.neb` uses `neb_` as the prefix, so those properties should be clearly distinct from any other optimization.

**Comment by bernstei** [comment]
Looks like it's already doing some of the things I suggested above, as I would have realized if I had read your initial message a bit more carefully.  I guess I do basically agree that keeping multiple computed properties from different `wfl.generate.*` functions is probably not useful.  I can think of two options:
 - default to the same prefix, so each one overwrites the previous, but then you can't tell which operation it was
 - do something like default all prefixes to `_last_op_<name of op>`, and manually overwrite any other property that starts with `last_op_`, so they overwrite, but do preserve the type of op.  
 
@jungsdao do you have an opinion between these two? Any other suggestions?

**Comment by jungsdao** [comment]
I understand that there could be some other situations where keeping values from different operations needs to be kept. So in that case, having history would be needed. But definitely using better separator like `:` would be better way of doing it. Having some redundant properties like `optimize_*` even after `neb_*` is not critical problem and that would be just something I can be aware of. 

But, would it be too complicated have two modes of overwriting which user can decide?
1. (default) keep history as now (but perhaps with better separator `:`)
1. Always overwrite with last operation

**Comment by bernstei** [comment]
There's already an `update_config_type` argument, which is currently boolean.  I can extend it easily enough.

**Comment by bernstei** [comment]
@jungsdao take a look at #311

**Comment by bernstei** [comment]
tests are passing, so I can merge if we agree that the updated behavior is good

**Comment by jungsdao** [comment]
I have tried this feature in the new branch and it seems to working as intended. 
Thank you for adapting this so quickly.
