### ISSUE TITLE
MACE descriptor 

### ISSUE THREAD

**Issue by jungsdao** [libAtoms/workflow#329]
I was using MACE descriptor with wfl and it would be nice to incorporate this script into main repository. 
However, I'm not sure how I should prepare pytest for MACE descriptor. 
It seems foundation model `mace_mp` doesn't have `get_descriptors` as one of its attributes but some sort of model should be uploaded to assets for this purpose.

**Comment by bernstei** [comment]
This runs into the fact that there's currently no robust way that I know of for ASE calculators to have non-standard results such as descriptors. If there's a standard ASE way to retrieve those, we can certainly save them in the calculator wrappers.

**Comment by bernstei** [comment]
OK, I think understand what you mean in terms of the model, but I don't exactly understand what you want from `wfl`. `MACECalculator` is just a generic ASE calculator - what about it needs something specific in `wfl`?

**Comment by jungsdao** [comment]
I thought it could be nice if I can use autoparallelization for calculating MACE descriptor and that was something specifically wanted to work with `wfl`. I wonder if this makes sense?

**Comment by bernstei** [comment]
I see.  It would be nice if `MACECalculator` would just compute the descriptors as part of computing energies, forces, etc, and then `get_descriptors` would just retrieve the saved info.  Then it would just work as part of the generic calculator wrapper, as long as it knew to save that information in info/arrays.

I'm not sure if `get_descriptor` works this way, though. I can check.

**Comment by jungsdao** [comment]
MACE descriptor is not calculated as a part of computing energy and forces. It should be calculated additionally as far as I know. Following is from MACE documentation. 
```
calculator = MACECalculator(model_paths='/content/checkpoints/MACE_model_run-123.model', device='cuda')
init_conf = read('BOTNet-datasets/dataset_3BPA/test_300K.xyz', '0')
descriptors = calculator.get_descriptors(init_conf)
```
Maybe I could add my script that calculates MACE calculator within wfl as a new PR but for now I don't have pytest for this.

**Comment by bernstei** [comment]
Also, note that is is quite easy to do in a tiny bit of code

```
from wfl.map import map as wfl_map
from mace.calculators.foundations_models import mace_mp

calc = mace_mp("small", default_dtype="float64")

def grab_desc(at, calc):
    at.new_array("desc", calc.get_descriptors(atoms=at))
    return at

a = wfl_map(ConfigSet(atoms), OutputSpec(), grab_desc, args=[calc], autopara_info={'num_python_subprocesses': n_proc})
```

**Comment by jungsdao** [comment]
Okay, then I think adding MACE descriptor to `wfl` would not be really beneficial.

**Comment by bernstei** [comment]
OK, feel free to close this issue unless you want to discuss some other asepct.
