### ISSUE TITLE
Bug: Potential issue when setting sigmas in gap_rss_set_config_sigmas_from_convex_hull.py

### ISSUE THREAD

**Issue by VladCarare** [libAtoms/workflow#36]
I have a gap-rss run started on 29th Nov 2021, with code version git https://github.com/gabor1/workflow/commit/968765772e20d9bab4e8ae21633a7a90bdb08e96-dirty.
This is related to the sigma-setting method in wfl/fit/modify_database/gap_rss_set_config_sigmas_from_convex_hull.py, but I noticed this method didn't change since, so the issues should still stand.

In my gap-rss run, I noticed in the training set for the final iteration that there are structures with energy_sigma = 0.001 (and 18 atoms say). 

However, when I recently tried to fit a GAP to my own structures, I found reasons to believe that the energy_sigma and virial_sigma values when set per config, are in fact not per atom, but are taken as a total for the atoms in that structure. So for example the energy_sigma = 0.001 for 18 atoms above corresponds to 0.0000(5) per atom. 

 In the attached picture I show a case where I set the sigmas to around 1meV/atom for each of the structures, but the resulting errors/atom are orders of magnitude smaller; hence the suspicion.![image](https://user-images.githubusercontent.com/50262527/155190034-e4ac187d-dea7-42df-8838-f71a8a2080c1.png) 
 
 This is corroborated by the bad force component fits from the gap-rss (note if github theme is dark one cannot read the labels): 
![image](https://user-images.githubusercontent.com/50262527/155190583-9e7797d4-2967-4315-8aac-f27eb7697000.png)
And the table of errors, where the force data has much larger errors in ratio to their sigma, than energy or virials do.
![Screenshot 2022-02-22 at 18 00 37](https://user-images.githubusercontent.com/50262527/155191761-e5097140-d482-47f1-b840-c67980efa637.png)

I spoke with Gabor and he concurs that when set per config, energy_sigma, virial_sigma and hessian_sigma should be scaled by the number of atoms. While force_sigma should not be scaled.

**Comment by bernstei** [comment]
I guess we can fix that, but it's going to be ugly, since it'll break backward compatibility, even if the new behavior is more correct.  Ugh.

**Comment by bernstei** [comment]
See #37.  Is it time to try to formalize _something_ having to do with requiring minimum version, etc, in the config file?

**Comment by VladCarare** [comment]
> will increase the energy and virial sigmas by factors of 6-24 (in the gap-rss iteration, more in the defect_MD iterations since cell sizes are bigger), but the force sigmas remaining the same.

But the resulting per atom sigma will be consistent with the force sigma regardless of the number of atoms, no? Sorry I'm a bit confused about what the problem may be with just multiplying the appended energy, virial and hessian sigma by the length of the atoms object.

**Comment by bernstei** [comment]
Even if you assume that the current heuristic `F_sigma = A sqrt(E_sigma)` is correct, there's no inherent value for `E_sigma` or  `A` - it's just a heuristic after all. When we make `E_sigma` larger than it used to be by multiplying by `sqrt(N)`, we have to decide if we want to keep the typical `E_sigma` the same (so reduce the value that's multiplied by `sqrt(N)`), or allow it to be larger, and then independently decide if we also want the `F_sigma` to be larger, or if we want to reduce `A` so that `F_sigma` is similar to what it was before.

**Comment by bernstei** [comment]
closed by #37

**Comment by bernstei** [comment]
@VladCarare Any problem if I close this issue?  I claim that #59 changed the heuristic to one that is more consistent with what we want.

**Comment by VladCarare** [comment]
No, it can be closed. I stopped testing with having a sigma-setting function some time ago, so I don't have anything to add.
