### ISSUE TITLE
docs branch has lots of docstring conflicts with what sphinx expects

### ISSUE THREAD

**Issue by bernstei** [libAtoms/workflow#4]
Lots of docstrings are not formatted according to what sphinx expects.  I will start to fix those, at least the ones that give warnings and I can figure out, and push to the docs branch.

**Comment by bernstei** [comment]
@gelzinyte Are you happy with the changes in my latest pushes (up to 110ceb21)?  I suspect there are lots of other ugly things in the docstrings, e.g. places where there are two separate sentences broken up by a single line break without punctuation, which sphinx just runs together.  But I think I got all the things bad enough to generate warnings.

**Comment by gelzinyte** [comment]
Yup, those changes look good.  I'm cleaning up and adding missing docstrings (e.g.  they're not even picked up sometimes), I think these should be sorted out too, while me/we are at it.

**Comment by bernstei** [comment]
Should we close this issue, or do you want to keep this issue open to remind us about the other problems?

**Comment by gelzinyte** [comment]
I think a documentation to-do reminder would be good, but I'll open a less specific dedicated issue
