### ISSUE TITLE
deprecate things that are not being done properly

### ISSUE THREAD

**Issue by bernstei** [libAtoms/workflow#44]
Deprecate bits of code that don't do things the workflow way, or just don't use it.  They can be updated to do it the right way (so they can be wrapped by `iterable_loop` (soon to be `autoparallelize`), or moved to some user-specific place.

`reactions_processing/`
`plotting/`
some things in `generate`, e.g.
   `neb`, `ts`, `vib`, `radicals`

some things in `cli.py`

**Comment by hheenen** [comment]
Considering the `plotting/`, I understand this is not linked to the `autoparallelize`, but I wonder if you don't want to provide some standard plots (one may add more) which could help users to monitor progress of potential training? 

If this is not wanted in the `wfl/` code maybe it makes sense to move it out of it, but keep it separately in the repo?

**Comment by bernstei** [comment]
I don't even know what's in plotting, but maybe we need a different repo for analysis?

**Comment by hheenen** [comment]
I mean that's up to you and maybe a separate repo is easier to maintain. I personally think that providing some analysis tools for workflow in the same repo would be more convenient, though. So far some of us have been using functions like `plot_ef_correlation.py` producing detailed energy and force correlation plots. Of course we could generalize and refactor the contained functions and add some more of our own which could fit in there -- we also happily do this if you chose to make a separate analysis repo.

**Comment by bernstei** [comment]
@gabor1 where should we put these things?

**Comment by gelzinyte** [comment]
Just to collect some other things to revise: 

* `devtools` (in particular `devtools/scripts/pretty_pca.py`)
* (to be continued)

**Comment by gelzinyte** [comment]
@bernstei what's wrong with `vib.py`?

**Comment by bernstei** [comment]
It's sort of OK, since it does use `ConfigSet`, but wouldn't it be more modular to have functions that just generate the necessary configurations, then use the existing autoparallelized generic eval loop, and then routines that analyze them?  Given that the calculations will almost certainly dominate the cost that seems like a more useful packaging of the work.

**Comment by gabor1** [comment]
providing a default rcParams would be good. not everyone controls their styles by rcParams files

**Comment by bernstei** [comment]
Comments on what's there now:
  - `reactions_processing/` : routines specific to @stenczelt workflow, not really workflow ops [note - by this reasoning, should gap-rss-iter-fit be moved out of workflow as well, or at least refactored in things that belong a things that don't?]
  - `plotting/` : nice for analysis, but not really using any workflow stuff
 - some things in `generate/`, 
   - `neb` : not using any workflow features
   - `ts` :  not using any workflow features
   - `vib` : using autoparallelize over configs xor Hessian displacements in each config. 
   - `radicals` : not using any workflow features
  
I think that `vib` has a good reason to stay, but all the others should probably be moved outside of `wfl`, whether that's some user or system specific directory distributed with the workflow, or entirely separate. I've tentatively moved them to `workflow/deprecated`. 

As for `vib`, we should think about the best interface, and perhaps also making it uniform with the equivalent functionality for periodic systems (using `phonopy`).  I have routines for that, but would need to think about how to unify the two interfaces.

**Comment by bernstei** [comment]
Current plan:
 - `reactions_processing`, `neb`, `ts`, `radicals` to `user/reactions` (name to be finalized)
 - `plotting` to `deprecate/plotting`, to be moved into a separate directory or repo for analysis
 - `vib` unchanged for now, pending thought about merging with `phononpy` based code for periodic systems.

@gabor1 sounds OK to you? Do we have a better name for the user directory for Tamas's code?

**Comment by stenczelt** [comment]
I am OK with deprecating them, if we even want to re-use them then git remembers everything. Feel free to go ahead with purging this part of the codebase.
