### ISSUE TITLE
wider support for nested datastructure in ConfigSet

### ISSUE THREAD

**Issue by bernstei** [libAtoms/workflow#47]
Support nested structure (list of lists) in `ConfigSet` under a wider range of circumstances. 

In memory: already supported

Files: already supported for multi-file with group iterator returning one group per file. Would need to be extended to single file with special tags, `num_of_group` and `num_in_group`, probably with additional tag `last_in_group`.

ABCD: will need tags, like single file suggestion

**Comment by hheenen** [comment]
Maybe fitting in this discussion would be a question why  for `ConfigSet`, "The input sources are mutually exclusive."  in initialization and the `.merge()` method (i.e. `input_files`, `input_queries`, `input_configs`). When manipulating, merging and mixing configurations mixing different inputs can be handy. E.g. when starting the workflow with existing data.

Writing a quick work-around is not problem on python level, but I wondered about this constraint.

**Comment by bernstei** [comment]
I agree that we need a discussion.  There are a couple of issues that came up when I decided to have this restriction.  One is that there's no obvious way of controlling the order of the configurations in the combined `ConfigSet`. The other is that it becomes quite hard to support the more advanced features, in particular things like file -> file mapping, and grouping.  These aren't necessarily insurmountable, though, and I agree that it'd sometimes be useful, so it's worth think about again.

**Comment by bernstei** [comment]
Maybe Support `n` inputs files to n output files without a dict? What about a _list_ with length `n` to automatically map to `n` output files

**Comment by bernstei** [comment]
#145 finally supports nested lists of lists in `ConfigSet`, both in memory and in file.  n files -> n file also supported. ABCD not supported now, can be revived when ABCD is revived. If any other use cases emerge, they should be discussed in a new issue.
