### ISSUE TITLE
replace `iterable_loop` with functools.partial-based decorator

### ISSUE THREAD

**Issue by bernstei** [libAtoms/workflow#48]
Replace cumbersome 
```
def run(inputs, outputs, arg1, ...):
    return iterable_loop(inputs, output, op, arg1, ...)
```
with decorator (although not using `@` syntax) `iloop`, which based on ideas [here](https://pythonicthoughtssnippets.github.io/2020/08/09/PTS13-rethinking-python-decorators.html)

May be able to do

```
def run(inputs, outputs, arg1, ...):
     # some code
run = functools.partial(iloop, run)
```
if we can figure out how to do `run.__doc__ = run.__doc__.format(iloop_docstring_post=iloop_docstring_post)`

**Comment by gelzinyte** [comment]
Just to make a note that current `iterable_loop` messages such as 
```
 Running <function evaluate_op at 0x145549c97160> with npool=16, chunksize=1
```
could be made slightly more helpful by displaying/having better names than `evaluate_op`, etc.
