### ISSUE TITLE
pytest shutil('orca') is a bad idea

### ISSUE THREAD

**Issue by bernstei** [libAtoms/workflow#66]
On some linux machines `orca` is a system executable that has nothing to do with the DFT code.  Maybe all the calculator tests should require that the desired executable be in a particular env var, similar to `ASE_{CALCULATOR}_COMMAND`

**Comment by bernstei** [comment]
The [ASE docs ](https://wiki.fysik.dtu.dk/ase/ase/calculators/orca.html) claim you can use the `ASE_ORCA_COMMAND` env var.  Is the orca path specification code still really needed?

**Comment by gelzinyte** [comment]
Didn't think `orca` wouldn't be unique, will change to `ASE_ORCA_COMMAND`.
